package com.hd.bean;

import java.util.Date;

public class ImageSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_source.id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_source.local_image_id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    private String localImageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_source.image_id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    private String imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_source.image_link
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    private String imageLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_source.local_image_path
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    private String localImagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_source.image_status
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    private Integer imageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_source.create_time
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_source.id
     *
     * @return the value of image_source.id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_source.id
     *
     * @param id the value for image_source.id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_source.local_image_id
     *
     * @return the value of image_source.local_image_id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public String getLocalImageId() {
        return localImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_source.local_image_id
     *
     * @param localImageId the value for image_source.local_image_id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public void setLocalImageId(String localImageId) {
        this.localImageId = localImageId == null ? null : localImageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_source.image_id
     *
     * @return the value of image_source.image_id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_source.image_id
     *
     * @param imageId the value for image_source.image_id
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_source.image_link
     *
     * @return the value of image_source.image_link
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public String getImageLink() {
        return imageLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_source.image_link
     *
     * @param imageLink the value for image_source.image_link
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink == null ? null : imageLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_source.local_image_path
     *
     * @return the value of image_source.local_image_path
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public String getLocalImagePath() {
        return localImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_source.local_image_path
     *
     * @param localImagePath the value for image_source.local_image_path
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public void setLocalImagePath(String localImagePath) {
        this.localImagePath = localImagePath == null ? null : localImagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_source.image_status
     *
     * @return the value of image_source.image_status
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public Integer getImageStatus() {
        return imageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_source.image_status
     *
     * @param imageStatus the value for image_source.image_status
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public void setImageStatus(Integer imageStatus) {
        this.imageStatus = imageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_source.create_time
     *
     * @return the value of image_source.create_time
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_source.create_time
     *
     * @param createTime the value for image_source.create_time
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}