package com.hd.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VideoSourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public VideoSourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNull() {
            addCriterion("video_id is null");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNotNull() {
            addCriterion("video_id is not null");
            return (Criteria) this;
        }

        public Criteria andVideoIdEqualTo(String value) {
            addCriterion("video_id =", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotEqualTo(String value) {
            addCriterion("video_id <>", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThan(String value) {
            addCriterion("video_id >", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThanOrEqualTo(String value) {
            addCriterion("video_id >=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThan(String value) {
            addCriterion("video_id <", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThanOrEqualTo(String value) {
            addCriterion("video_id <=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLike(String value) {
            addCriterion("video_id like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotLike(String value) {
            addCriterion("video_id not like", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdIn(List<String> values) {
            addCriterion("video_id in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotIn(List<String> values) {
            addCriterion("video_id not in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdBetween(String value1, String value2) {
            addCriterion("video_id between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotBetween(String value1, String value2) {
            addCriterion("video_id not between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andLinkUrlIsNull() {
            addCriterion("link_url is null");
            return (Criteria) this;
        }

        public Criteria andLinkUrlIsNotNull() {
            addCriterion("link_url is not null");
            return (Criteria) this;
        }

        public Criteria andLinkUrlEqualTo(String value) {
            addCriterion("link_url =", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotEqualTo(String value) {
            addCriterion("link_url <>", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlGreaterThan(String value) {
            addCriterion("link_url >", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlGreaterThanOrEqualTo(String value) {
            addCriterion("link_url >=", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlLessThan(String value) {
            addCriterion("link_url <", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlLessThanOrEqualTo(String value) {
            addCriterion("link_url <=", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlLike(String value) {
            addCriterion("link_url like", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotLike(String value) {
            addCriterion("link_url not like", value, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlIn(List<String> values) {
            addCriterion("link_url in", values, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotIn(List<String> values) {
            addCriterion("link_url not in", values, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlBetween(String value1, String value2) {
            addCriterion("link_url between", value1, value2, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andLinkUrlNotBetween(String value1, String value2) {
            addCriterion("link_url not between", value1, value2, "linkUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNull() {
            addCriterion("image_url is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNotNull() {
            addCriterion("image_url is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlEqualTo(String value) {
            addCriterion("image_url =", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotEqualTo(String value) {
            addCriterion("image_url <>", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThan(String value) {
            addCriterion("image_url >", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("image_url >=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThan(String value) {
            addCriterion("image_url <", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThanOrEqualTo(String value) {
            addCriterion("image_url <=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLike(String value) {
            addCriterion("image_url like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotLike(String value) {
            addCriterion("image_url not like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIn(List<String> values) {
            addCriterion("image_url in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotIn(List<String> values) {
            addCriterion("image_url not in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlBetween(String value1, String value2) {
            addCriterion("image_url between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotBetween(String value1, String value2) {
            addCriterion("image_url not between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andResourceNameIsNull() {
            addCriterion("resource_name is null");
            return (Criteria) this;
        }

        public Criteria andResourceNameIsNotNull() {
            addCriterion("resource_name is not null");
            return (Criteria) this;
        }

        public Criteria andResourceNameEqualTo(String value) {
            addCriterion("resource_name =", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotEqualTo(String value) {
            addCriterion("resource_name <>", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameGreaterThan(String value) {
            addCriterion("resource_name >", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("resource_name >=", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLessThan(String value) {
            addCriterion("resource_name <", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLessThanOrEqualTo(String value) {
            addCriterion("resource_name <=", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLike(String value) {
            addCriterion("resource_name like", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotLike(String value) {
            addCriterion("resource_name not like", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameIn(List<String> values) {
            addCriterion("resource_name in", values, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotIn(List<String> values) {
            addCriterion("resource_name not in", values, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameBetween(String value1, String value2) {
            addCriterion("resource_name between", value1, value2, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotBetween(String value1, String value2) {
            addCriterion("resource_name not between", value1, value2, "resourceName");
            return (Criteria) this;
        }

        public Criteria andPraiseRateIsNull() {
            addCriterion("praise_rate is null");
            return (Criteria) this;
        }

        public Criteria andPraiseRateIsNotNull() {
            addCriterion("praise_rate is not null");
            return (Criteria) this;
        }

        public Criteria andPraiseRateEqualTo(String value) {
            addCriterion("praise_rate =", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateNotEqualTo(String value) {
            addCriterion("praise_rate <>", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateGreaterThan(String value) {
            addCriterion("praise_rate >", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateGreaterThanOrEqualTo(String value) {
            addCriterion("praise_rate >=", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateLessThan(String value) {
            addCriterion("praise_rate <", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateLessThanOrEqualTo(String value) {
            addCriterion("praise_rate <=", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateLike(String value) {
            addCriterion("praise_rate like", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateNotLike(String value) {
            addCriterion("praise_rate not like", value, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateIn(List<String> values) {
            addCriterion("praise_rate in", values, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateNotIn(List<String> values) {
            addCriterion("praise_rate not in", values, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateBetween(String value1, String value2) {
            addCriterion("praise_rate between", value1, value2, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andPraiseRateNotBetween(String value1, String value2) {
            addCriterion("praise_rate not between", value1, value2, "praiseRate");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNull() {
            addCriterion("video_time is null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNotNull() {
            addCriterion("video_time is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeEqualTo(String value) {
            addCriterion("video_time =", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotEqualTo(String value) {
            addCriterion("video_time <>", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThan(String value) {
            addCriterion("video_time >", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThanOrEqualTo(String value) {
            addCriterion("video_time >=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThan(String value) {
            addCriterion("video_time <", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThanOrEqualTo(String value) {
            addCriterion("video_time <=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLike(String value) {
            addCriterion("video_time like", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotLike(String value) {
            addCriterion("video_time not like", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIn(List<String> values) {
            addCriterion("video_time in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotIn(List<String> values) {
            addCriterion("video_time not in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeBetween(String value1, String value2) {
            addCriterion("video_time between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotBetween(String value1, String value2) {
            addCriterion("video_time not between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andWatchCountIsNull() {
            addCriterion("watch_count is null");
            return (Criteria) this;
        }

        public Criteria andWatchCountIsNotNull() {
            addCriterion("watch_count is not null");
            return (Criteria) this;
        }

        public Criteria andWatchCountEqualTo(Integer value) {
            addCriterion("watch_count =", value, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountNotEqualTo(Integer value) {
            addCriterion("watch_count <>", value, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountGreaterThan(Integer value) {
            addCriterion("watch_count >", value, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("watch_count >=", value, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountLessThan(Integer value) {
            addCriterion("watch_count <", value, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountLessThanOrEqualTo(Integer value) {
            addCriterion("watch_count <=", value, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountIn(List<Integer> values) {
            addCriterion("watch_count in", values, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountNotIn(List<Integer> values) {
            addCriterion("watch_count not in", values, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountBetween(Integer value1, Integer value2) {
            addCriterion("watch_count between", value1, value2, "watchCount");
            return (Criteria) this;
        }

        public Criteria andWatchCountNotBetween(Integer value1, Integer value2) {
            addCriterion("watch_count not between", value1, value2, "watchCount");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeIsNull() {
            addCriterion("video_upload_time is null");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeIsNotNull() {
            addCriterion("video_upload_time is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeEqualTo(String value) {
            addCriterion("video_upload_time =", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeNotEqualTo(String value) {
            addCriterion("video_upload_time <>", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeGreaterThan(String value) {
            addCriterion("video_upload_time >", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeGreaterThanOrEqualTo(String value) {
            addCriterion("video_upload_time >=", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeLessThan(String value) {
            addCriterion("video_upload_time <", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeLessThanOrEqualTo(String value) {
            addCriterion("video_upload_time <=", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeLike(String value) {
            addCriterion("video_upload_time like", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeNotLike(String value) {
            addCriterion("video_upload_time not like", value, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeIn(List<String> values) {
            addCriterion("video_upload_time in", values, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeNotIn(List<String> values) {
            addCriterion("video_upload_time not in", values, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeBetween(String value1, String value2) {
            addCriterion("video_upload_time between", value1, value2, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andVideoUploadTimeNotBetween(String value1, String value2) {
            addCriterion("video_upload_time not between", value1, value2, "videoUploadTime");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryIsNull() {
            addCriterion("host_directory is null");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryIsNotNull() {
            addCriterion("host_directory is not null");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryEqualTo(String value) {
            addCriterion("host_directory =", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryNotEqualTo(String value) {
            addCriterion("host_directory <>", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryGreaterThan(String value) {
            addCriterion("host_directory >", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryGreaterThanOrEqualTo(String value) {
            addCriterion("host_directory >=", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryLessThan(String value) {
            addCriterion("host_directory <", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryLessThanOrEqualTo(String value) {
            addCriterion("host_directory <=", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryLike(String value) {
            addCriterion("host_directory like", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryNotLike(String value) {
            addCriterion("host_directory not like", value, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryIn(List<String> values) {
            addCriterion("host_directory in", values, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryNotIn(List<String> values) {
            addCriterion("host_directory not in", values, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryBetween(String value1, String value2) {
            addCriterion("host_directory between", value1, value2, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andHostDirectoryNotBetween(String value1, String value2) {
            addCriterion("host_directory not between", value1, value2, "hostDirectory");
            return (Criteria) this;
        }

        public Criteria andVideoSourceIsNull() {
            addCriterion("video_source is null");
            return (Criteria) this;
        }

        public Criteria andVideoSourceIsNotNull() {
            addCriterion("video_source is not null");
            return (Criteria) this;
        }

        public Criteria andVideoSourceEqualTo(String value) {
            addCriterion("video_source =", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceNotEqualTo(String value) {
            addCriterion("video_source <>", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceGreaterThan(String value) {
            addCriterion("video_source >", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceGreaterThanOrEqualTo(String value) {
            addCriterion("video_source >=", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceLessThan(String value) {
            addCriterion("video_source <", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceLessThanOrEqualTo(String value) {
            addCriterion("video_source <=", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceLike(String value) {
            addCriterion("video_source like", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceNotLike(String value) {
            addCriterion("video_source not like", value, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceIn(List<String> values) {
            addCriterion("video_source in", values, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceNotIn(List<String> values) {
            addCriterion("video_source not in", values, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceBetween(String value1, String value2) {
            addCriterion("video_source between", value1, value2, "videoSource");
            return (Criteria) this;
        }

        public Criteria andVideoSourceNotBetween(String value1, String value2) {
            addCriterion("video_source not between", value1, value2, "videoSource");
            return (Criteria) this;
        }

        public Criteria andDownStatusIsNull() {
            addCriterion("down_status is null");
            return (Criteria) this;
        }

        public Criteria andDownStatusIsNotNull() {
            addCriterion("down_status is not null");
            return (Criteria) this;
        }

        public Criteria andDownStatusEqualTo(Integer value) {
            addCriterion("down_status =", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusNotEqualTo(Integer value) {
            addCriterion("down_status <>", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusGreaterThan(Integer value) {
            addCriterion("down_status >", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("down_status >=", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusLessThan(Integer value) {
            addCriterion("down_status <", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusLessThanOrEqualTo(Integer value) {
            addCriterion("down_status <=", value, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusIn(List<Integer> values) {
            addCriterion("down_status in", values, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusNotIn(List<Integer> values) {
            addCriterion("down_status not in", values, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusBetween(Integer value1, Integer value2) {
            addCriterion("down_status between", value1, value2, "downStatus");
            return (Criteria) this;
        }

        public Criteria andDownStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("down_status not between", value1, value2, "downStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_source
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 20 21:52:53 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}