package com.hd.bean;

import java.util.Date;

public class VideoSource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.id
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.video_id
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.link_url
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.image_url
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.resource_name
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.praise_rate
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String praiseRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.video_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String videoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.watch_count
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private Integer watchCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.video_upload_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String videoUploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.host_directory
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String hostDirectory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.video_source
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private String videoSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.create_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_source.down_status
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    private Integer downStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.id
     *
     * @return the value of video_source.id
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.id
     *
     * @param id the value for video_source.id
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.video_id
     *
     * @return the value of video_source.video_id
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.video_id
     *
     * @param videoId the value for video_source.video_id
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.link_url
     *
     * @return the value of video_source.link_url
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.link_url
     *
     * @param linkUrl the value for video_source.link_url
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.image_url
     *
     * @return the value of video_source.image_url
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.image_url
     *
     * @param imageUrl the value for video_source.image_url
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.resource_name
     *
     * @return the value of video_source.resource_name
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.resource_name
     *
     * @param resourceName the value for video_source.resource_name
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.praise_rate
     *
     * @return the value of video_source.praise_rate
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getPraiseRate() {
        return praiseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.praise_rate
     *
     * @param praiseRate the value for video_source.praise_rate
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setPraiseRate(String praiseRate) {
        this.praiseRate = praiseRate == null ? null : praiseRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.video_time
     *
     * @return the value of video_source.video_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getVideoTime() {
        return videoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.video_time
     *
     * @param videoTime the value for video_source.video_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setVideoTime(String videoTime) {
        this.videoTime = videoTime == null ? null : videoTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.watch_count
     *
     * @return the value of video_source.watch_count
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public Integer getWatchCount() {
        return watchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.watch_count
     *
     * @param watchCount the value for video_source.watch_count
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setWatchCount(Integer watchCount) {
        this.watchCount = watchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.video_upload_time
     *
     * @return the value of video_source.video_upload_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getVideoUploadTime() {
        return videoUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.video_upload_time
     *
     * @param videoUploadTime the value for video_source.video_upload_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setVideoUploadTime(String videoUploadTime) {
        this.videoUploadTime = videoUploadTime == null ? null : videoUploadTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.host_directory
     *
     * @return the value of video_source.host_directory
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getHostDirectory() {
        return hostDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.host_directory
     *
     * @param hostDirectory the value for video_source.host_directory
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setHostDirectory(String hostDirectory) {
        this.hostDirectory = hostDirectory == null ? null : hostDirectory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.video_source
     *
     * @return the value of video_source.video_source
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public String getVideoSource() {
        return videoSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.video_source
     *
     * @param videoSource the value for video_source.video_source
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setVideoSource(String videoSource) {
        this.videoSource = videoSource == null ? null : videoSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.create_time
     *
     * @return the value of video_source.create_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.create_time
     *
     * @param createTime the value for video_source.create_time
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_source.down_status
     *
     * @return the value of video_source.down_status
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public Integer getDownStatus() {
        return downStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_source.down_status
     *
     * @param downStatus the value for video_source.down_status
     *
     * @mbggenerated Mon Aug 20 16:16:04 CST 2018
     */
    public void setDownStatus(Integer downStatus) {
        this.downStatus = downStatus;
    }
}