package com.hd.mapper;

import com.hd.bean.ImageSource;
import com.hd.bean.ImageSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    long countByExample(ImageSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int deleteByExample(ImageSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int insert(ImageSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int insertSelective(ImageSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    List<ImageSource> selectByExample(ImageSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    ImageSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") ImageSource record, @Param("example") ImageSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int updateByExample(@Param("record") ImageSource record, @Param("example") ImageSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int updateByPrimaryKeySelective(ImageSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_source
     *
     * @mbg.generated Mon Aug 20 21:52:15 CST 2018
     */
    int updateByPrimaryKey(ImageSource record);
    
    
    int updateImageStatus(ImageSource record);
}