package com.hd.mapper;

import com.hd.bean.VideoSource;
import com.hd.bean.VideoSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    long countByExample(VideoSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int deleteByExample(VideoSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int insert(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int insertSelective(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    List<VideoSource> selectByExample(VideoSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    VideoSource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") VideoSource record, @Param("example") VideoSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int updateByExample(@Param("record") VideoSource record, @Param("example") VideoSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int updateByPrimaryKeySelective(VideoSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_source
     *
     * @mbg.generated Mon Aug 20 21:52:53 CST 2018
     */
    int updateByPrimaryKey(VideoSource record);
}